문자열 계산기 구현
zunior-team/string-calculator pull request #2
Opened 2020-01-09 04:44 UTC by junwoochoi

문자열 계산기 구현해 보았습니다.

 들여쓰기를 하나만 쓰려고 하니 어색하네요...ㅎ
 과제 중 질문이 생겼는데, Scanner를 사용해서 Input을 받는 부분에 대해서 테스트를 작성해야하나 고심하다가, 따로 작성하지 않는 것으로 일단은 제출하였는데 다른 분들은 그 부분에 대해서 테스트를 작성해야하는 것이 맞다고 생각하시는 지 궁금합니다!

코멘트 부탁드립니다! 🙏

2020-01-10 00:19 UTC, gale34 commented on src/main/java/com/teamzunior/stringcalculator/calculator/InputListener.java
> +    private void printEndMessage() {
사소하긴 한데..listen()에는 startMessage가 먼저 나오는데 뒤에 구현은 endMessage가 먼저나와서요, printStartMessage()랑 printEndMessage() 위치를 바꾸면 어떨까요?

2020-01-10 00:28 UTC, gale34 commented on src/main/java/com/teamzunior/stringcalculator/calculator/StringCalculatorElements.java
> +    private List<CalculateType> calculateTypes;
일급 컬렉션을 쓰는 건 어떨까요?

2020-01-10 00:30 UTC, gale34 reviewed
깔끔한 코드 잘 봤습니다!
특히 테스트 코드들은 많이 보고 배워야겠네요..감사합니다!

2020-01-10 01:45 UTC, junwoochoi commented on src/main/java/com/teamzunior/stringcalculator/calculator/InputListener.java
> +    private void printEndMessage() {
앗 그러게요... 인텔리제이의 `Extract Function` 을 사용하다보니 나중에 따로 뺀 `printEndMessage()`가 위로 올라와 버렸네요! 감사합니다!

2020-01-10 01:45 UTC, junwoochoi commented on src/main/java/com/teamzunior/stringcalculator/calculator/StringCalculatorElements.java
> +    private List<CalculateType> calculateTypes;
앗 일급 컬렉션을 쓰려고 처음 생각하며 만든 객체였는데 말씀을 듣고보니 일급 컬렉션이 아니네요......ㅎㅎ 수정해야겠습니다 감사합니다

2020-01-10 04:37 UTC, nokchax reviewed
Math내의 함수들을 사용할 수도있었네요, 깔끔한 코드 잘봤습니다.
몇가지 코멘트 남겨봐요

2020-01-10 04:37 UTC, nokchax commented on src/main/java/com/teamzunior/stringcalculator/calculator/CalculateType.java
> +        return Arrays.stream(values())
이렇게 기호를 enum에 추가하면 기호를 enum에 매칭하기 위해 사용하는 map을 없앨수 있겠네요.
물론 매번 반복문을 돌아야 하긴 하지만요..
enum내부의 타입이 자주 늘어나는 경우에는 실수를 줄여주는 방법이 될것 같아요 :)

2020-01-10 04:37 UTC, nokchax commented on src/main/java/com/teamzunior/stringcalculator/calculator/Calculator.java
> +        calculateMap.put(CalculateType.SUM, Math::addExact);
Math내의 함수들은 저도 적용해봐야 할거 같아요

2020-01-10 04:37 UTC, nokchax commented on src/main/java/com/teamzunior/stringcalculator/calculator/Calculator.java
> +    public static int calculate(int a, int b, CalculateType calculateType) {
a,b와 같은 변수명은 사용하지 않는게 좋을거 같아요.
적어도 수학에서 많이 사용하는 변수명인 x,y로 바꾸는게 좋아보입니다.

2020-01-10 04:37 UTC, nokchax commented on src/main/java/com/teamzunior/stringcalculator/calculator/InputListener.java
> +            input = getTrimmedNextLine();
```
input = getTrimmedNextLine();
```
위의 코드가 중복되는데

```
while(!END_SIGN.equalsIgnoreCase(input = getTrimmedNextLine()) {}
```
를 이용하면 중복을 제거할 수 있어요! 물론 가독성을 떨어지지만 공유차원에서 남겨봐요

2020-01-10 04:37 UTC, nokchax commented on src/main/java/com/teamzunior/stringcalculator/calculator/InputListener.java
> +        if (tokens.length < 3) {
`3`을 `MINIMUM_INPUT_LENGTH` 처럼 정적 변수로 빼는게 좋을것 같습니다.

2020-01-10 04:37 UTC, nokchax commented on src/main/java/com/teamzunior/stringcalculator/calculator/StringCalculatorElements.java
> +    private List<CalculateType> calculateTypes;
numbers와 calculateTypes 두개를 각가의 일급 컬렉션으로 빼면, 두 객체 사이의 메세지 전달이 많이 복잡해질거 같아요,
제가 생각하기에 연산자와 피연산자를 묶어서 가는게 좋아 보이는데 여러분들 생각은 어떤가요?

2020-01-10 04:37 UTC, nokchax commented on src/main/java/com/teamzunior/stringcalculator/calculator/StringCalculatorElements.java
> +        int result = numbers.get(0);
인풋값이 ""인 경우에는 null pointer exception이 발생할것 같은데 맞나요?

2020-01-10 04:37 UTC, nokchax commented on src/test/java/com/teamzunior/stringcalculator/caculator/CalculateTypeTest.java
> +    }
여기는 하나로 합칠 수 있을거 같아요, display name이 조금 길어지긴 하겠지만,
@NullAndEmptySource는 다른 Source 어노테이션과 같이 사용 가능합니다

2020-01-10 04:37 UTC, nokchax commented on src/main/java/com/teamzunior/stringcalculator/calculator/StringCalculatorElements.java
> +        final int lengthOfElements = elements.length;
쉽게 구할수 있는 length값을 따로 빼서, 함수의 매개변수 갯수를 늘리는건 좋아보이지 않아요

2020-01-10 05:19 UTC, junwoochoi commented on src/main/java/com/teamzunior/stringcalculator/calculator/CalculateType.java
> +        return Arrays.stream(values())
넵! 매번 반복문을 돌아야하니 타입이 너무 많아지면, 성능적으로는 손해가 있긴 하겠네요... :(

2020-01-10 05:20 UTC, junwoochoi commented on src/main/java/com/teamzunior/stringcalculator/calculator/Calculator.java
> +    public static int calculate(int a, int b, CalculateType calculateType) {
앗, 초반에 a,b로 사용하다가 나중에 테스트 코드 쪽은 first, second 와 같이 바꿔줬었는데 테스트 코드쪽을 보느라 실제 구현 쪽을 놓쳤네요. 감사합니다 :)

2020-01-10 05:21 UTC, junwoochoi commented on src/main/java/com/teamzunior/stringcalculator/calculator/InputListener.java
> +            input = getTrimmedNextLine();
오 저렇게도 작성이 가능하군요. 공유 감사합니다! 😄

2020-01-10 05:23 UTC, junwoochoi commented on src/main/java/com/teamzunior/stringcalculator/calculator/InputListener.java
> +        if (tokens.length < 3) {
원시값을 그대로 사용했었네요... 
 적용해보겠습니다 :)

2020-01-10 05:31 UTC, junwoochoi commented on src/main/java/com/teamzunior/stringcalculator/calculator/StringCalculatorElements.java
> +        final int lengthOfElements = elements.length;
두번 이상 사용하는 것들은 변수에 담아주려고 하고 있는데, array의 length 같은 경우는 더 여러번 나올때 빼도 될 것 같네요 ㅎㅎ

2020-01-10 05:35 UTC, junwoochoi commented on src/main/java/com/teamzunior/stringcalculator/calculator/StringCalculatorElements.java
> +        int result = numbers.get(0);
인풋값이 `""` 즉, Empty인 경우는 `InputListener`의 `validateElementsCount`함수에서 `length`가 3이하라서 `IllegalArgumentException`이 떨어지도록 되어있습니다. 
해당 관련 테스트를 작성하긴 해야겠네요.

2020-01-10 05:37 UTC, junwoochoi commented on src/test/java/com/teamzunior/stringcalculator/caculator/CalculateTypeTest.java
> +    }
오 좋은 의견 감사합니다. 적용해볼게요! 😃

2020-01-10 07:10 UTC, cglee079 requested changes
감사합니다. 깔끔한 코드 잘보았습니다ㅎㅎ!
몇 가지 코멘트를 남겨보았어요!

2020-01-10 07:10 UTC, cglee079 commented on src/main/java/com/teamzunior/stringcalculator/calculator/Calculator.java
> +    private static Map<CalculateType, BiFunction<Integer, Integer, Integer>> calculateMap = new HashMap<>();
`Enum` 타입이 `key`값이라면, 
`EnumMap`, `EnumSet`을 사용하는것도 좋을것 같아요,(성능면에서 더 빨라요 :)! )
https://siyoon210.tistory.com/142

2020-01-10 07:10 UTC, cglee079 commented on src/test/java/com/teamzunior/stringcalculator/caculator/CalculatorTest.java
> +    @DisplayName("오버플로우시 Exception을 던진다")
오홍, 배우고 갑니당!

2020-01-10 07:10 UTC, cglee079 commented on src/main/java/com/teamzunior/stringcalculator/calculator/CalculateType.java
> +        return Arrays.stream(values())
혹시, 확장에 열려있다면, 
여기서 `sign`이 중복될경우에 예외처리를 해야되지 않을까요?
`map`의 `key`값은 유니크를 보장하지만, 여기서는 유니크하지 않을 수도 있을것같아서요!
휴먼에러 ㅠㅠ...

2020-01-10 07:27 UTC, junwoochoi commented on src/main/java/com/teamzunior/stringcalculator/calculator/Calculator.java
> +    private static Map<CalculateType, BiFunction<Integer, Integer, Integer>> calculateMap = new HashMap<>();
우오! 감사합니다! 부끄럽지만 난생 처음 들어봐여 ....ㅎㅎ 좋은 걸 또 배웠군요 🙇

2020-01-10 08:03 UTC, junwoochoi commented on src/main/java/com/teamzunior/stringcalculator/calculator/CalculateType.java
> +        return Arrays.stream(values())
@cglee079  오 ... 그런 경우도 있을 수 있네요. 그런 경우는 compile 단에서 체크를 해주면 좋을 것 같은데 한 번 고민해보겠습니다!

2020-01-10 12:30 UTC, nokchax commented on src/main/java/com/teamzunior/stringcalculator/calculator/Calculator.java
> +    private static Map<CalculateType, BiFunction<Integer, Integer, Integer>> calculateMap = new HashMap<>();
오 저도 첨 봤어요ㅋㅋ 공유 감사합니다

2020-01-10 17:56 UTC, pasudo123 reviewed
좋은 코드 잘 보았습니다. !
스트림을 능숙하게 사용하신게 인상 깊었습니다.
궁금한 부분 일부 코멘트 작성하였습니다. 🛩

2020-01-10 17:56 UTC, pasudo123 commented on src/main/java/com/teamzunior/stringcalculator/calculator/InputListener.java
> +            final String[] tokens = input.split(BLANK_DELIMITER);
String 클래스의 `split()` 메소드의 경우에 안에 인자값의 정규식 스트링을 받을 수 있는 걸로 알고 있습니다.
`public static final String BLANK_DELIMITER = "\\s";` 로 표현하는 것에 대해서 어떻게 생각하시나요?

`" "` 로 써도 되지만 기본 인자로 받는 형식을 java api doc 에는 regexp 라는 문구가 있어서 물어봅니다. 😄 
[관련링크](https://www.tutorialspoint.com/java/lang/string_split.htm)

2020-01-10 17:56 UTC, pasudo123 commented on src/main/java/com/teamzunior/stringcalculator/calculator/StringCalculator.java
> +    }
`StringCalculator` 클래스가 제공하는 부분이 상수와 스태틱한 메소드이면, 생성자를 private 으로 만드는 건 어떨까요? 
생성자는 기본이 디폴트 생성자인테, 외부에서 작성되는 부분을 컴파일 타임에 감지하면 좀 더 안정적이지 않을까 생각이 들어 물어봅니다. 😃

2020-01-10 17:56 UTC, pasudo123 commented on src/test/java/com/teamzunior/stringcalculator/caculator/CalculatorTest.java
> +    @ParameterizedTest(name = "{0} + {1}  -> {2}")
저는 안에 좀 장황하게 글로 설명했는데, 기호와 화살표로 하는게 테스트 코드 결과내용을 보기에 가독성이 훨씬 좋네요.
저도 이렇게 해야겠습니다. !! 👍

2020-01-13 05:08 UTC, gale34 approved these changes
코드 잘 봤습니다!

2020-01-13 05:47 UTC, nokchax reviewed
고생하셨습니다~

2020-01-13 05:47 UTC, nokchax commented on src/main/java/com/teamzunior/stringcalculator/calculator/StringCalculator.java
> +        return result;
Expression 개념을 추가해서 이전보다 가독성이 좋아졌어요 👍

2020-01-13 11:39 UTC, cglee079 reviewed
코드 잘 봤습니다 :). 수고하셨습니다!

2020-01-13 11:39 UTC, cglee079 commented on src/main/java/com/teamzunior/stringcalculator/calculator/Expression.java
> +        return result;
질문) 혹시 인스턴스 변수 `isCalculated()`와 `result`의 용도는 무엇인지 알 수 있을까요??

2020-01-14 00:24 UTC, merged

2020-01-14 00:45 UTC, junwoochoi commented on src/main/java/com/teamzunior/stringcalculator/calculator/Expression.java
> +        return result;
@cglee079 이미 계산이 되서 본인의 계산결과를 가지고 있다면, 다시 계산할 필요없이 본인이 가지고 있는 계산 결과를 리턴하라는 의미로 사용하였습니다. 현재 요구사항에서는 각 Expression의 결과가 두번 이상 호출될 일은 없으니... 굳이 작성하지 않아도 될 것 같기도 한데, 작성당시에는 왠지 있으면 좋지 않을 까 싶어서 저런식으로 작성해봤어요!