[PARK] 20190109 문자열 계산기 구현
zunior-team/string-calculator pull request #5
Opened 2020-01-09 09:29 UTC by pasudo123

### 생각해본것.
- 문자열 계산을 이용하는데, 연산 기호를 어떻게 보유하고 있을지.
- 연산기호를 통해서 값을 보관하고 있으면 어떻게 보관하는 것이 좋은지, 원시값으로 보관하는 부분도 생각했지만 자류구조인 스택을 이용했습니다. (아마 예전 알고리즘 풀던 기억이 남아 적용을 해보았습니다.)
- 함수형 인터페이스, 람다 관련 효율적인 사용방법 및 도대체 왜? 사용할까 라는 고민.
- 테스트 코드 작성 시, private 접근 메소드에 대한 작성 이유 반드시 해야하는지? [링크](https://medium.com/@vadimpushtaev/how-to-test-private-methods-4bc57d4410ff)

조금이나마 junit5 와 TDD 그리고 문자열계산기에 대해서 생각해볼 수 있는 시간이었습니다.

2020-01-09 13:12 UTC, junwoochoi requested changes
좋은 코드 잘 읽었습니다!
저 같은 경우는 private 함수는 따로 테스트를 작성할 생각을 해본 적은 없는데, 이번 기회에 저도 깊은 고민을 해봐야겠습니다.....ㅎㅎ

많이 배우고 갑니다! 👍

2020-01-09 13:12 UTC, junwoochoi commented on src/main/java/com/teamzunior/stringcalculator/calculator/Calculator.java
> +    public static Calculator createOfCalculator() {
사용시 호출을 `Calculator.createOfCalculator` 라고 하니까  Calculator를 굳이 두번 써줄 필요는 없을 것 같아요! 
```suggestion
    public static Calculator newInstance() {
```
```suggestion
    public static Calculator create() {
```

정적 팩토리 메소드 패턴 👍

2020-01-09 13:12 UTC, junwoochoi commented on src/main/java/com/teamzunior/stringcalculator/calculator/Validator.java
> +        throw new IllegalArgumentException("입력 값이 널 또는 빈 공백 문자열입니다.");
```java
if(StringUtils.isEmpty(line)){
    throw new IllegalArgumentException("입력 값이 널 또는 빈 공백 문자열입니다.");
}
```

로 표현하면 더 간결할 것 같아요!

2020-01-09 13:12 UTC, junwoochoi commented on src/main/java/com/teamzunior/stringcalculator/calculator/Calculator.java
> +        return pot.getValue();
현재 Calculator 객체와 ValuePot 객체 사이에 결합도가 너무 높은 것 같습니다. 
`객체지향의 사실과 오해`라는 책에서는 각 객체들 사이는 메시지를 통해서만 협력하고, 서로의 자세한 구현은 각 객체의 자율성에 맡겨야 한다고 합니다. 좋은 책이니 시간 날 때 한번 읽어보시길 추천드립니다! 👍 
 

책의 내용에 대해 [잘 정리된 글](https://github.com/cheese10yun/TIL/blob/master/OOP/%EA%B0%9D%EC%B2%B4%EC%A7%80%ED%96%A5%EC%9D%98%EC%82%AC%EC%8B%A4%EA%B3%BC%EC%98%A4%ED%95%B4.md)이 있어서 책을 읽기전에 한번 보는 것도 좋을 것 같습니다 :D

2020-01-09 13:12 UTC, junwoochoi commented on src/main/java/com/teamzunior/stringcalculator/calculator/OperatorComputer.java
> +        return Optional.empty();
여기서 존재하지 않으면 바로 Exception을 던져도 되지 않을까요?

2020-01-09 13:12 UTC, junwoochoi commented on src/main/java/com/teamzunior/stringcalculator/calculator/Calculator.java
> +     */
이미 코드만으로도 설명이 충분해서 굳이 주석이 필요없을 것 같습니다.
[클린코드 4장](https://kwosu87.gitbooks.io/clean-code/content/Chapter%2004%20-%20%EC%A3%BC%EC%84%9D.html)의 주석 챕터에 설명이 잘 되어 있어요 :)

2020-01-09 13:12 UTC, junwoochoi commented on src/main/java/com/teamzunior/stringcalculator/calculator/ValuePot.java
> +                    : this.optionalComputer;
아마 들여쓰기 때문에 사용하신 것 같지만, 혹시 몰라 코멘트 달아봅니다.
저 같은 경우는 삼항 연산자는 정말 간단한 상황이 아니면 가독성이 떨어진다고 생각해서 사용하지 않으려  하고 있는데요...
코멘트 달면서 [스택오버플로우](https://stackoverflow.com/questions/694814/ternary-operator-bad-or-good-practice)를 찾아봤는데 각자 다들 의견이 다르긴 하네요!
성동 담당님은 어떻게 생각하시나요?

2020-01-09 13:12 UTC, junwoochoi commented on src/test/java/com/teamzunior/stringcalculator/calculator/OperatorComputerTest.java
> +    @DisplayName("연산 컴퓨터는 [덧셈] 연산을 수행한다.")
ParameterizedTest인데 하나의 Parameter에 대해서만 테스트하고 있어요!
그냥 Test를 사용하시거나 , MethodSource로 `a`,`b`, `computer`, `result `을  받아서 사용하면 더 다양한 상황을 테스트 할 수 있지 않을까요?

2020-01-09 13:12 UTC, junwoochoi commented on src/test/java/com/teamzunior/stringcalculator/calculator/ValidatorTest.java
> +    }
두 함수가 같은 파라미터를 받아서 테스트하는 것 같은데 맞나요?

2020-01-09 13:35 UTC, pasudo123 commented on src/test/java/com/teamzunior/stringcalculator/calculator/ValidatorTest.java
> +    }
같은 파라미터를 받아서 테스트하는 것 맞습니다. `null` 과 empty 값을 받는데 하나는 `@CsvSource` 애노테이션을 이용해서 null 문자열을 null 로 컨버팅을 하는 형태로 취해보았고, 다른 하나는 `@NullAndEmptySource` 를 통해서 null 값을 받아오도록 하였습니다. 

저렇게 한 이유는 한가지 방식만 알아도 무방하지만, 두가지 방식으로 동일한 로직에 대해서 테스트를 해보고 싶었습니다. 😅

2020-01-09 13:38 UTC, pasudo123 commented on src/test/java/com/teamzunior/stringcalculator/calculator/OperatorComputerTest.java
> +    @DisplayName("연산 컴퓨터는 [덧셈] 연산을 수행한다.")
넵 맞습니다. ㅎㅎ 저도 MethodSource 를 통해서 `Arguments`  로 받아오는 형태로 취하려고 하다가 `@EnumSource` 에 대한 사용방법을 익히고자 한번 사용해보았습니다. ! 예리하십니다...

`@MethodSource`  를 통한 테스트도 같이 넣어두도록 하겠습니다. ! 👍

2020-01-09 13:56 UTC, pasudo123 commented on src/main/java/com/teamzunior/stringcalculator/calculator/ValuePot.java
> +                    : this.optionalComputer;
개인적 의견으로는 저 정도의 구문정도는 이해하는데 큰 무리가 없다고 판단해서 `삼항연산자` 를 넣게 되었습니다.. 실제 실무 코드 내에서도 삼항연산자를 쓰긴 쓰는데, 어느 특정 변수에 값을 할당할 때 삼항연산자를 저는 아래와 같이 부분에서 사용하고 있습니다.

- null 여부 판단 이후 값 할당.
- max or min 판단 이후 값 할당.
- true or false 판단 이후 값 할당.

보통 대부분의 조건문들도 위와 같은 내용을 보고 분기처리를 실시하는데, 삼항연산자를 항상 쓰는 건 아니지만 바로 값을 할당하면서 리턴하는 형태로 짧게 코드를 취하기 좋다고 생각해서 쓰고있습니다. 😄 

더불어서 삼항연산자를 마치 `메소드 체이닝` 처럼 아래와 같이 쓰는건 지양해야한다고 생각합니다. 
`삼항연산자 중첨`
```java
Object variable = (a < 10) 
  ? 10
  :  (a < 50) 
      ? 50 
      : blahblah
```

그리고 제가 예전에 글을 봤는게 출처가 생각이 안나네요. 삼항연산자를 `?` 와 `:` 기호를 한 줄에 쓰기보단 개행해서 각각 분리해서 쓰는게 가독성이 더 좋다고해서 저렇게 쓰고 있습니다. (완전 짧으면 한줄로 하는게 더 좋을 듯 싶어요.)

[관련링크](https://coderanch.com/t/397290/java/style-ternary-operator-return-statement)

2020-01-09 13:58 UTC, pasudo123 commented on src/main/java/com/teamzunior/stringcalculator/calculator/Calculator.java
> +     */
넵 지우도록 하겠습니다! 👍

2020-01-09 14:03 UTC, pasudo123 commented on src/main/java/com/teamzunior/stringcalculator/calculator/OperatorComputer.java
> +        return Optional.empty();
여기 부분에서 연산자 문자열이 진입한 블록인데, `Optional.empty()` 를 반환한 부분은 이후에 다른 매칭될 연산자가 있을지 없을지 모르기 때문에 현재 할당된 `OperaterComputer` 존재여부의 척도로 사용하고 있습니다.

`Exception` 을 던진다는 생각은 하지 않았는데 만약 Exception 을 처리하게 된다면 해당 메소드를 호출하는 부분에서 `catch` 를 하여 그에 따른 로직으로 처리하는 방향으로 갈 수도 있겠군요. 👍

2020-01-09 14:04 UTC, pasudo123 commented on src/main/java/com/teamzunior/stringcalculator/calculator/Validator.java
> +        throw new IllegalArgumentException("입력 값이 널 또는 빈 공백 문자열입니다.");
아하 넵넵 !  감사합니다. !

2020-01-09 14:04 UTC, pasudo123 commented on src/main/java/com/teamzunior/stringcalculator/calculator/Calculator.java
> +    public static Calculator createOfCalculator() {
`create()` 표현이 더 간결하겠군요 👍

2020-01-09 14:09 UTC, pasudo123 commented on src/main/java/com/teamzunior/stringcalculator/calculator/Calculator.java
> +        return pot.getValue();
객체간의 의존관계를 낮추어야 하는데 많은 연습이 필요할 것 같습니다. 링크 감사합니다.!! 👨‍💻

2020-01-10 01:09 UTC, gale34 commented on src/main/java/com/teamzunior/stringcalculator/Main.java
> +        final String line = scanner.nextLine();
사용자 입력 받는 모듈도 분리하면 좋을 것 같아요

2020-01-10 01:10 UTC, gale34 commented on src/main/java/com/teamzunior/stringcalculator/calculator/Calculator.java
> +    public BigDecimal computeStringValue(final String line) {
파라미터로 String을 받으니까 compute()로 대신해도 되지 않을까요?

2020-01-10 01:13 UTC, gale34 commented on src/main/java/com/teamzunior/stringcalculator/calculator/Calculator.java
> +        final int size = elements.length;
stream을 사용하면 깔끔하게 보일 것 같아요

2020-01-10 01:39 UTC, gale34 commented on src/main/java/com/teamzunior/stringcalculator/calculator/ValuePot.java
> +        for(OperatorComputer computer : computers){
이 과정에서 결국엔 IF문이 4번 발생하지 않을까요? 
지금 만들어두신 OperatorComputer 이랑 OperatorSet을 활용하시면 한번에 원하는 optionalComputer를 얻을 것 같은데..혹시 제가 파악 못한 로직 상 이유가 있을까요?

2020-01-10 01:40 UTC, gale34 commented on src/main/java/com/teamzunior/stringcalculator/calculator/ValuePot.java
> +        pot.push(optionalComputer
optionalComputer가 compute 과정에서만 쓰이는 거라면 인스턴스 변수가 아니라 파라미터로 넘겨도 되지 않을까요?

2020-01-10 01:42 UTC, gale34 commented on src/test/java/com/teamzunior/stringcalculator/util/NullableConverter.java
> +    protected Object convert(Object source, Class<?> targetType) throws ArgumentConversionException {
아 이런 경우도 고려하셨군요! 잘 봤습니다:)

2020-01-10 01:44 UTC, gale34 commented on src/main/java/com/teamzunior/stringcalculator/calculator/ValuePot.java
> +final class ValuePot {
개인적으로 ValuePot 명칭이 모호한 것 같아서..명확한 이름으로 바꾸면 좋을 것 같아요!

2020-01-10 01:45 UTC, gale34 reviewed
코드 잘 봤습니다!
여러 가지로 많이 고민해보신 것 같아서 저도 찾아보게 됐네요:)

2020-01-10 01:59 UTC, gale34 commented on src/test/java/com/teamzunior/stringcalculator/calculator/ValuePotTest.java
> + * https://medium.com/@vadimpushtaev/how-to-test-private-methods-4bc57d4410ff
음..해당 글에 달린 댓글들도 읽어봄직하네요

2020-01-10 06:55 UTC, cglee079 reviewed
책임을 최대한 분할하려고한 코드가 인상깊었습니다 :)
감사합니다!
몇가지 코멘트를 남겨봤어요!

2020-01-10 06:55 UTC, cglee079 commented on src/main/java/com/teamzunior/stringcalculator/calculator/ValuePot.java
> +        }
이 로직에 대한 책임은 Enum 타입에 static 메소드로 넘겨도 될거같아요.  `OperatorComputer.parse` 처럼요!

2020-01-10 06:55 UTC, cglee079 commented on src/main/java/com/teamzunior/stringcalculator/calculator/ValuePot.java
> +                    : this.optionalComputer;
`Optional` 이라면, `Optional#orElse()`를 쓰는건 어떨까요?

2020-01-10 06:55 UTC, cglee079 commented on src/main/java/com/teamzunior/stringcalculator/operator/OperatorSet.java
> +    }};
혹시, HashSet을 사용하지 않은 이유가있을까요?
`OperatorSet`을 `map`으로 사용하는 로직은 안보여써요!

또 추가적으로 키값이 `enum`타입이라면,  `EnumSet`, `EnumMap`이 성능이 더 좋습니다 :) !!

2020-01-10 13:18 UTC, nokchax reviewed
수고하셨습니다. 몇가지 코멘트 남겨뒀어요. 다른분들과 마찬가지로 TDD를 진행하고 있는만큼, 테스트 코드 먼저 작성 후에 코드구현을 하는식으로 해보세요, 또 git에 커밋하는 단위도 작게해서 자주 커밋하는 것을 한번 적용해보세요. 저 같은 경우는 잘게 나눌수록 나중에 코드 복구하기도 쉬워지고, 코드 추적하기도 편하더라구요 (커밋량이 많아보이는 부수적인 효과까지!ㅎㅎ)

2020-01-10 13:18 UTC, nokchax commented on src/main/java/com/teamzunior/stringcalculator/calculator/OperatorComputer.java
> +    public BigDecimal calculate(final BigDecimal a, final BigDecimal b) {
a, b 와 같은 의미없는 변수명은 쓰지 않는게 좋을거 같아요
foreOperand나 backOperand 하다못해 수학에서 사용하는 x,y 같은 변수명이 좋을것 같습니다!

2020-01-10 13:18 UTC, nokchax commented on src/main/java/com/teamzunior/stringcalculator/calculator/Calculator.java
> +        Validator.checkValidOnInputString(line);
아래에 써뒀지만 단순 empty체크만 하는거라면 굳이 유딜리티 클래스를 사용하지 않아도 될거 같아요!

2020-01-10 13:18 UTC, nokchax commented on src/main/java/com/teamzunior/stringcalculator/calculator/Validator.java
> +    static void checkValidOnInputString(final String line) {
함수명과 구현 내용간에 이질감이 있는거 같아요, 구현 내용을 보지 않고 메소드명만 확인했을때, 인풋 스트링의 유효성 검증이라고 하면 여러가지 체크가 들어갈 수 있을거 같은데, 실제로 구현된 내용을 보면 인풋값이 비어있는지만 체크하고 있으니까 isEmpty()정도로만 명명했어도 되지 않을까요?
그리고 이 함수를 사용하고 있는곳 또한 한군데 밖에 없기 때문에, 굳이 따로 클래스로 뺄 필요는 없어보여요

2020-01-10 13:18 UTC, nokchax commented on src/main/java/com/teamzunior/stringcalculator/calculator/ValuePot.java
> +        if(pot.empty()) {
`stack.isEmpty()`만 있는줄 알았는데, 하나 배워갑니다 ㅎㅎ

2020-01-10 13:18 UTC, nokchax commented on src/main/java/com/teamzunior/stringcalculator/operator/OperatorSet.java
> +        put(MULTIPLY_SYMBOL, new Object());
Object() 로 초기화 하신 이유가 있나요?

2020-01-10 13:18 UTC, nokchax commented on src/test/java/com/teamzunior/stringcalculator/calculator/ValuePotTest.java
> + * https://medium.com/@vadimpushtaev/how-to-test-private-methods-4bc57d4410ff
저도 읽어보겠습니다 감사합니다

2020-01-10 13:18 UTC, nokchax commented on src/test/java/com/teamzunior/stringcalculator/operator/OperatorSetTest.java
> +    @ParameterizedTest(name = "\"{0}\" 문자가 들어왔고, 불린타입은 {1}을 리턴했습니다.")
이건 저도 적용해 봐야겠네요

2020-01-10 13:18 UTC, nokchax commented on src/main/java/com/teamzunior/stringcalculator/calculator/ValuePot.java
> +        for(OperatorComputer computer : computers){
이 로직은 `Enum`으로 넘기는게 좋아보여요(어떻게 보면 OperatorComputer.values()가 getter라고 볼수 있으니깐요), 또 operatorSet을 이용해서 symbol과 enum타입을 매칭시켜 놓는다면, for문을 돌릴 필요도 없어보입니다

2020-01-11 01:27 UTC, pasudo123 commented on src/main/java/com/teamzunior/stringcalculator/Main.java
> +        final String line = scanner.nextLine();
맞아요! 저도 이 부분에 대해서도 진행했어야 했는데.. 안했네요. 넣도록 하겠습니다 ! 😄

2020-01-11 02:01 UTC, pasudo123 reviewed
작성해주신 코멘트 하나하나 보았습니다. 부족한 부분에 대해서는 피드백 적용하도록 하겠습니다.
코멘트 작성해주신 선임님, 담당님들 감사합니다 ! 👍 👍

2020-01-11 02:01 UTC, pasudo123 commented on src/main/java/com/teamzunior/stringcalculator/calculator/Validator.java
> +    static void checkValidOnInputString(final String line) {
아 넵.. `Validator` 클래스 내에 메소드가 명이 장황합니다. 저도 이 부분을 작성하면서 크게 인지를 못했는데 메소드 명을 변경하고 따로 클래스로 빼둔걸 없애도 무방하다고 생각합니다. 👍 👍

2020-01-11 02:01 UTC, pasudo123 commented on src/main/java/com/teamzunior/stringcalculator/calculator/Calculator.java
> +        Validator.checkValidOnInputString(line);
넵 그게 좋겠어요. 그리고 메소드 명도 다시 보니깐 너무 장황해서 뭘 하는지 잘 모르겠네요 ㅠ 수정하도록 하겠습니다.!

2020-01-11 02:01 UTC, pasudo123 commented on src/main/java/com/teamzunior/stringcalculator/calculator/Calculator.java
> +    public BigDecimal computeStringValue(final String line) {
`pot.compute()` 메소드로 바로 받아도 되냐는 말씀이신지 이해를 못했습니다 ㅠ. 다만 그런 말씀이시면, 해당 로직 내에 있는 `splitLineByWhiteSpace` 부분이나 `checkLine` 부분도 따로 선처리가 진행되거나 아예 `compute()` 메소드 내로 옮기는 것으로 고려해도 괜찮을 것 같습니다. 👍

2020-01-11 02:01 UTC, pasudo123 commented on src/main/java/com/teamzunior/stringcalculator/calculator/Calculator.java
> +        final int size = elements.length;
넵! 스트림을 사용을 꾸준히 하면서 익히면 더 깔끔해질 것 같아요 !

2020-01-11 02:01 UTC, pasudo123 commented on src/main/java/com/teamzunior/stringcalculator/calculator/OperatorComputer.java
> +    public BigDecimal calculate(final BigDecimal a, final BigDecimal b) {
아하 넵 처음에 `frontValue` `backValue` 라는 명칭을 사용했다가 단순 a, b 로 사용하였는데 이런 부분도 좀 더 의미가 가도록 하는게게 명확하겠어요. 👍 👍

2020-01-11 02:01 UTC, pasudo123 commented on src/main/java/com/teamzunior/stringcalculator/calculator/ValuePot.java
> +final class ValuePot {
😅 사실 스택을 쓰면서 값을 담아두는 항아리?! 같은 개념으로 valuePot 이라고 명명을 했습니다. 신경쓰인 부분이라 변경하도록 하겠습니다.!! 😄

2020-01-11 02:01 UTC, pasudo123 commented on src/main/java/com/teamzunior/stringcalculator/calculator/ValuePot.java
> +        for(OperatorComputer computer : computers){
사실 for 구문 돌면서 OperatorComputer type 이 네개로 구성되니 네번의 if 문이 발생하는 것 맞습니다.
맵을 이용해서 작성하면 if 문 발생을 줄일 수가 있겠군요.  감사합니다. 해당 내용은 반영토록 하겠습니다 !! 👍

2020-01-11 02:01 UTC, pasudo123 commented on src/main/java/com/teamzunior/stringcalculator/calculator/ValuePot.java
> +        for(OperatorComputer computer : computers){
넵넵 OperatorSet 을 이용해서 key : 상수, value : enum 형태로 취하면 저도 더 간결해지겠다는 생각이 들었습니다. 이 부분에 대해서 반영하도록 하겠습니다 !! 👍

2020-01-11 02:01 UTC, pasudo123 commented on src/main/java/com/teamzunior/stringcalculator/calculator/ValuePot.java
> +                    : this.optionalComputer;
아! 정말 그렇게 하는게 좋겠네요. `isPresent()` 를 쓰지 않고 바로 orElse() 로 하면 더 간결해지겠군요 !! 👍

2020-01-11 02:01 UTC, pasudo123 commented on src/main/java/com/teamzunior/stringcalculator/calculator/ValuePot.java
> +        }
오호 감사합니다. 그렇게 진행하도록 하는게 좋겠네요 ! :)

2020-01-11 02:01 UTC, pasudo123 commented on src/main/java/com/teamzunior/stringcalculator/calculator/ValuePot.java
> +        pot.push(optionalComputer
이 부분에 대해서 이해를 잘 못하였는데, 다시 한번 설명해주실 수 있나요 ? 😭

2020-01-11 02:01 UTC, pasudo123 commented on src/main/java/com/teamzunior/stringcalculator/operator/OperatorSet.java
> +        put(MULTIPLY_SYMBOL, new Object());
값의 존재여부 판단을 위한 더미 형태로 삽입했습니다.. 그래서 해당 `SYMBOL` 존재를 위해 체크여부 용도입니다.
이 내용과 enum 관련 내용을 value 로 넣어주는게 좀 더 가독성 면에서 코드 퀄리티 면에서 좋다고 생각이 듭니다 !!
예전에 알고리즘 풀 때도 이런식으로 자주 풀었어서 약간의 습관성이 있는듯 합니다.. ㅠ

2020-01-11 02:01 UTC, pasudo123 commented on src/main/java/com/teamzunior/stringcalculator/operator/OperatorSet.java
> +    }};
HashSet 도 내부적으로 HashMap 으로 구현되어 있는걸로 알고있습니다.
그래서 해시맵에 키 값이 HashSet 의 요소 값으로 들어가고 밸류 값이 new Object() 형태로 더미로 쌓이고 있어서 두 개에 큰 차이가 없다고 판단해서 저는 해시맵으로 사용하였습니다. ㅎㅎ

```java
public class HashSet<E>
    extends AbstractSet<E>
    implements Set<E>, Cloneable, java.io.Serializable
{
    static final long serialVersionUID = -5024744406713321676L;

    private transient HashMap<E,Object> map;

    // Dummy value to associate with an Object in the backing Map
    private static final Object PRESENT = new Object();

    /**
     * Constructs a new, empty set; the backing <tt>HashMap</tt> instance has
     * default initial capacity (16) and load factor (0.75).
     */
    public HashSet() {
        map = new HashMap<>();
    }

// 

public boolean add(E e) {
        return map.put(e, PRESENT)==null;
    }
```
그리고 개인적 선호도가 셋보다는 맵에 있었습니다. 😅 

추가로 enumSet 이랑 enumMap 성능은 처음 들어봤는데 저도 관련된 자료 찾아봐야겠네요 감사합니다. !👍

2020-01-13 00:08 UTC, junwoochoi commented on src/main/java/com/teamzunior/stringcalculator/calculator/ValuePot.java
> +                    : this.optionalComputer;
`Optional`에서는 `orElse()`와 `orElseGet()`이 존재하는데, 둘 사이에 차이가 있습니다.

`optional`이라는 `Optional` 변수가 존재하고, `getOther()`라는 메소드가 존재한다고 가정합니다.
이런 상황에서 `optional.orElse(getOther())`의 경우에는 `optional`이 `empty`이든 아니든 항상 실행되고, `optional.orElseGet(getOther())`는 `optional`이 `empty`일 때만 실행된다고 합니다!

보통 대부분의 상황에서 저희가 필요한  건 후자인 경우가 많으니, `orElse`보다는 `orElseGet`을 사용하는 습관을 들이도록 해야될 것 같아요!

[링크](https://dzone.com/articles/optionalorelse-vs-optionalorelseget)에 간단한 실험결과와 함께 설명이 되어있으니 한번 보셔도 좋을 거 같아요! 👍

2020-01-13 00:15 UTC, cglee079 commented on src/main/java/com/teamzunior/stringcalculator/calculator/ValuePot.java
> +                    : this.optionalComputer;
오홍, 몰랐던내용인데 감사합니다 👍 !

2020-01-13 00:29 UTC, junwoochoi approved these changes
수정된 코드 잘 봤습니다! ㅎㅎ

2020-01-13 00:29 UTC, junwoochoi commented on src/main/java/com/teamzunior/stringcalculator/ArithmeticConsole.java
> +    static void welcomePrintMessage() {
`welcomPrintMessage()`, `byePrintMessage()` 보다는 `printWelcomeMessage()`, `printByeMessage()`가 더 이해하기 쉽고, 자연스러워 보일 것 같습니다!
[참고한 글](https://effectiveprogramming.tistory.com/entry/%EC%A2%8B%EC%9D%80-%EB%A9%94%EC%86%8C%EB%93%9C-%EC%9D%B4%EB%A6%84-%EB%A7%8C%EB%93%9C%EB%8A%94-%EB%B2%95)
> 메소드 명칭 = 명령형 동사 + 목적어

2020-01-13 01:36 UTC, cglee079 commented on src/main/java/com/teamzunior/stringcalculator/operator/OperatorSet.java
> +    }};
음, 저는 두개의 타입에는 큰 차이가 있지 않을까 생각합니다..

`HashSet`은 `Set`인터페이스의 구현체인것이 중요한 부분이라 생각합니다.
이는 곧 추후에 다른 `Set` 구현체로 대체 가능함과, 
`Set`으로 추상화 가능함을 의미하기 때문입니다.

예를 들어, `CollectionUtils`라는 메소드를 보면 다음과 같은상황이 있을 수 있습니다.
//Set, Map은 이미 유니크해서 적절한 메소드는 아니지만...
``` java
CollectionUtils.hasUniqueObject(new HashMap<String>()); // Error
CollectionUtils.hasUniqueObject(new HashSet<String>()); // Success!
```

2020-01-13 05:24 UTC, gale34 approved these changes
코드 잘 봤습니다!
저도 welcomPrintMessage(), byePrintMessage()의 메소드 명을 동사 먼저 쓰는게 낫지 않을까 싶네요:)

2020-01-13 05:43 UTC, nokchax reviewed
고생하셨습니다~

2020-01-13 11:13 UTC, cglee079 commented
수고하셨습니다 :) !!

2020-01-13 14:44 UTC, pasudo123 commented on src/main/java/com/teamzunior/stringcalculator/calculator/ValuePot.java
> +                    : this.optionalComputer;
감사합니다 !!

2020-01-13 15:01 UTC, pasudo123 commented on src/main/java/com/teamzunior/stringcalculator/calculator/ValuePot.java
> +                    : this.optionalComputer;
링크내용을 보다가 이것저것 확인하니,  `orElseGet` 은 람다식으로 쓸 수 있네요. `orElseGet(() -> something())` 형태로 써서, 준우담당님 말씀대로 해당 값이 `empty` 또는 `null` 인 경우에서 메소드 수행을 하고 해당 값을 반환하고, 반대로 값이 존재하는 경우에는 메소드 호출 및 값을 반환하네요.

- `orElse(something())` : 바로 메소드 수행 .
- `orElseGet(() -> something())` : 값 null 또는 empty 여부 확인 이후 메소드 수행.

[링크](https://www.daleseo.com/java8-optional-after/)

2020-01-13 15:08 UTC, pasudo123 commented on src/main/java/com/teamzunior/stringcalculator/operator/OperatorSet.java
> +    }};
아하 넵넵 Set 을 추상화해서 다른 Set 구현체로 대체가능함에 저도 동의합니다. ^^; 서로 간의 직접적으로 하고자하는 역할이 다르기 때문에 별도로 존재하겠죠.. ㅠ 사실 해시맵의 익숙함이 있었습니다 ㅎㅎ;

그래서 제 코드 상에서 `HashMap` 을 `HashSet` 대신으로 쓰기에 무리가 없다고 판단했고, 그에 따른 요구사항에 대한 특이점이 없어서 구현했습니다.. 😅

2020-01-13 22:51 UTC, merged